In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
#import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
## your code
d = np.arange(1,20)
ans = np.power(2,d)/d
print(ans)

[2.00000000e+00 2.00000000e+00 2.66666667e+00 4.00000000e+00
 6.40000000e+00 1.06666667e+01 1.82857143e+01 3.20000000e+01
 5.68888889e+01 1.02400000e+02 1.86181818e+02 3.41333333e+02
 6.30153846e+02 1.17028571e+03 2.18453333e+03 4.09600000e+03
 7.71011765e+03 1.45635556e+04 2.75941053e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [42]:
## your code
ones = np.ones((6,1))/10
twos = np.ones((6,1))/5
# возводим в степень 0,1
deg = np.ones((1,6))*3*np.arange(0,6)
ones = ones ** np.transpose(deg)
# возводим в степень 0,2
deg = np.ones((1,6))*4*np.arange(0,6)
twos = twos ** np.transpose(deg)

ans = np.sum(ones*twos)
print(ans)

1.00000160000256


**3.** Создать нулевую матрицy $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [43]:
## your code
mat = np.zeros((8,8))
mat = mat + np.eye(8,k=-4)+np.eye(8,k=-2)+np.eye(8,k=0)+np.eye(8,k=2)+np.eye(8,k=4)+np.eye(8,k=-6)+np.eye(8,k=6)
print(mat)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [44]:
X = np.random.random((5, 2))

## your code
# расстояние
r = np.sqrt( np.power(X[:,0],2) + np.power(X[:,1],2) )
print(r)
# угол
d = np.arctan(X[:,1]/X[:,0])
print(d)

[0.5052755  0.72325869 0.71626545 0.50110922 0.79807886]
[1.4120503  0.62333243 0.25305742 0.31846396 1.10681928]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [45]:
X = np.random.random((10, 10))

## your code
#print(X)
np.unravel_index( np.argmax(X), X.shape )

(4, 4)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [46]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code

#print(np.power(X[:,0] - y[0,0],2) + np.power(X[:,1] - y[0,1],2))
np.argmin(np.power(X[:,0] - y[0,0],2) + np.power(X[:,1] - y[0,1],2))

0

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [47]:
## your code
@np.vectorize
def func(x):
    if x<0:
        return x**2 + 2*x +6
    elif x<=2:
        return x+6
    else:
        return x**2+4*x-4
X = np.arange(-3,3)
func(X)

array([9, 6, 5, 6, 7, 8])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [48]:
X = np.random.random((10, 10))

## your code
ans = X - np.mean(X,axis = 1,keepdims = True)
np.mean(ans,axis = 1)

array([ 1.22124533e-16, -1.11022302e-17,  4.44089210e-17, -3.33066907e-17,
       -4.44089210e-17,  4.44089210e-17,  4.44089210e-17, -6.66133815e-17,
        5.55111512e-17,  2.22044605e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [49]:
X = np.random.normal(loc=5, scale=2., size=1000)

In [50]:
## my code
mean = np.mean(X) 
print('Среднее',mean)
variance = np.mean(np.power((X - mean),2))
print('Дисперсия',variance)

Среднее 4.9751731560990855
Дисперсия 4.026876096577068


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [51]:
## your code
mat = np.zeros((5,5))
mat += np.eye(5,5,-3)[::-1] + 2 * np.eye(5,5,-2)[::-1] + 3 * np.eye(5,5,-1)[::-1] +\
4 * np.eye(5,5)[::-1] + np.eye(5,5,2)[::-1] + 2 * np.eye(5,5,3)[::-1] + 3 * np.eye(5,5,4)[::-1]
print(mat)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 0.]
 [2. 3. 4. 0. 1.]
 [3. 4. 0. 1. 2.]
 [4. 0. 1. 2. 3.]]
